export const itemsType = [
  {
    type: "woman",
    underType: "cloth",
    data: [
      "coats",
      "sweatshirts and sweaters",
      "winter coats",
      "jeans",
      "T-shirts",
      "navy",
      "shirts",
      "trousers",
      "suits",
      "underwear",
    ],
  },
  {
    type: "woman",
    underType: "shoes",
    data: [
      "winter boots",
      "lace-up shoes",
      "sneakers and sneakers",
      "shoes",
      "oksfords",
      "moccasins",
      "boots",
      "business footwear",
      "sports shoes",
      "outdoor footwear",
    ],
  },

  {
    type: "man",
    underType: "cloth",
    data: [
      "coats",
      "sweaters_and_sweatshirts",
      "jackets_and_blazers",
      "dresses",
      "shirts and tops",
      "blouses and shirts",
      "jeans",
      "pants",
      "skirts",
      "underwear",
    ],
  },
  {
    type: "man",
    underType: "shoes",
    data: [
      "sneakers",
      "boots",
      "shoes",
      "boots",
      "shuttles",
      "high heeled shoes",
      "ballerina",
      "sports shoes",
      "vegan footwear",
      "on a wide foot",
    ],
  },
];
